## from repo root
#### Cleaning docker
# docker rm -f $(docker ps -aq)
# docker rmi -f $(docker images -q)
# docker system prune -a --volumes
#### Setting up
# docker-compose down -v
# docker compose up --build
# webrtc -> http://localhost:3000
# byond server listening on port 1337
version: "3.9"
services:
  webrtc:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  byond:
    build:
      context: .
      dockerfile: Dockerfile.byond
      args:
        PROJECT_NAME: voice_chat_byond        # <- change if your .dme is named different
        DME_FILE: voice_chat_byond.dme        # <- set exact .dme filename
        BYOND_VERSION: "516"
        BYOND_BUILD: "516.1666"
    ports:
      - "1337:1337"
    restart: unless-stopped